"""Hand-curated Indian stock universe + fundamentals for demo mode.

Numbers approximate real businesses but are NOT live. They are deliberately
spread to make the scoring engine produce clearly differentiated results
across mind-map archetypes (value / quality / dividend).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DemoStock:
    ticker: str
    name: str
    sector: str
    industry: str
    metrics: dict[str, float]


# All metric values are canonical chamak units (see rules/metrics.py).
# percent fields are in actual percent (15 = 15%), ratios are absolute.
DEMO_STOCKS: list[DemoStock] = [
    # ============ IT services — high quality, premium valuation =============
    DemoStock("TCS", "Tata Consultancy Services", "IT", "IT Services",
        {"pe": 30, "pb": 14, "ps": 6, "ev_ebitda": 20, "dividend_yield": 1.4,
         "roe": 48, "roce": 60, "roa": 25, "net_margin": 19, "operating_margin": 24,
         "gross_margin": 45, "revenue_growth": 7, "earnings_growth": 9,
         "revenue_cagr_3y": 13, "eps_cagr_3y": 12, "debt_to_equity": 0.05,
         "interest_coverage": 95, "current_ratio": 2.6, "quick_ratio": 2.5,
         "fcf_yield": 4.2, "promoter_holding": 72, "pledged_pct": 0,
         "years_since_listing": 21, "market_cap_cr": 1400000, "price": 3850, "beta": 0.7}),
    DemoStock("INFY", "Infosys", "IT", "IT Services",
        {"pe": 27, "pb": 9, "ps": 5.5, "ev_ebitda": 17, "dividend_yield": 2.4,
         "roe": 32, "roce": 40, "roa": 19, "net_margin": 17, "operating_margin": 22,
         "gross_margin": 40, "revenue_growth": 6, "earnings_growth": 8,
         "revenue_cagr_3y": 12, "eps_cagr_3y": 11, "debt_to_equity": 0.08,
         "interest_coverage": 60, "current_ratio": 2.2, "quick_ratio": 2.1,
         "fcf_yield": 4.5, "promoter_holding": 14, "pledged_pct": 0,
         "years_since_listing": 31, "market_cap_cr": 720000, "price": 1750, "beta": 0.8}),
    DemoStock("HCLTECH", "HCL Technologies", "IT", "IT Services",
        {"pe": 25, "pb": 6, "ps": 4, "ev_ebitda": 16, "dividend_yield": 3.5,
         "roe": 23, "roce": 30, "roa": 14, "net_margin": 15, "operating_margin": 20,
         "gross_margin": 37, "revenue_growth": 8, "earnings_growth": 7,
         "revenue_cagr_3y": 14, "eps_cagr_3y": 9, "debt_to_equity": 0.12,
         "interest_coverage": 45, "current_ratio": 2.0, "quick_ratio": 1.9,
         "fcf_yield": 4.8, "promoter_holding": 60, "pledged_pct": 0,
         "years_since_listing": 24, "market_cap_cr": 460000, "price": 1700, "beta": 0.9}),
    DemoStock("WIPRO", "Wipro", "IT", "IT Services",
        {"pe": 23, "pb": 4, "ps": 3, "ev_ebitda": 14, "dividend_yield": 0.4,
         "roe": 14, "roce": 19, "roa": 10, "net_margin": 13, "operating_margin": 17,
         "gross_margin": 32, "revenue_growth": 1, "earnings_growth": -3,
         "revenue_cagr_3y": 8, "eps_cagr_3y": 4, "debt_to_equity": 0.21,
         "interest_coverage": 25, "current_ratio": 2.4, "quick_ratio": 2.3,
         "fcf_yield": 5.1, "promoter_holding": 73, "pledged_pct": 0,
         "years_since_listing": 27, "market_cap_cr": 260000, "price": 490, "beta": 0.85}),

    # ============ Banks — varied quality / valuations =====================
    DemoStock("HDFCBANK", "HDFC Bank", "Banking", "Private Bank",
        {"pe": 19, "pb": 2.8, "ps": 3.2, "ev_ebitda": 0, "dividend_yield": 1.2,
         "roe": 17, "roce": 0, "roa": 1.9, "net_margin": 24, "operating_margin": 0,
         "gross_margin": 0, "revenue_growth": 18, "earnings_growth": 12,
         "revenue_cagr_3y": 19, "eps_cagr_3y": 14, "debt_to_equity": 7.5,
         "interest_coverage": 0, "current_ratio": 0, "quick_ratio": 0,
         "fcf_yield": 0, "promoter_holding": 0, "pledged_pct": 0,
         "years_since_listing": 28, "market_cap_cr": 1300000, "price": 1700, "beta": 1.05}),
    DemoStock("ICICIBANK", "ICICI Bank", "Banking", "Private Bank",
        {"pe": 17, "pb": 3.0, "ps": 3.0, "ev_ebitda": 0, "dividend_yield": 0.9,
         "roe": 18, "roce": 0, "roa": 2.1, "net_margin": 26, "operating_margin": 0,
         "gross_margin": 0, "revenue_growth": 22, "earnings_growth": 28,
         "revenue_cagr_3y": 21, "eps_cagr_3y": 33, "debt_to_equity": 6.5,
         "interest_coverage": 0, "current_ratio": 0, "quick_ratio": 0,
         "fcf_yield": 0, "promoter_holding": 0, "pledged_pct": 0,
         "years_since_listing": 27, "market_cap_cr": 860000, "price": 1230, "beta": 1.1}),
    DemoStock("SBIN", "State Bank of India", "Banking", "PSU Bank",
        {"pe": 11, "pb": 1.6, "ps": 1.2, "ev_ebitda": 0, "dividend_yield": 1.7,
         "roe": 16, "roce": 0, "roa": 1.0, "net_margin": 17, "operating_margin": 0,
         "gross_margin": 0, "revenue_growth": 12, "earnings_growth": 24,
         "revenue_cagr_3y": 11, "eps_cagr_3y": 35, "debt_to_equity": 12.0,
         "interest_coverage": 0, "current_ratio": 0, "quick_ratio": 0,
         "fcf_yield": 0, "promoter_holding": 56, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 680000, "price": 760, "beta": 1.2}),
    DemoStock("KOTAKBANK", "Kotak Mahindra Bank", "Banking", "Private Bank",
        {"pe": 21, "pb": 2.9, "ps": 4.2, "ev_ebitda": 0, "dividend_yield": 0.1,
         "roe": 14, "roce": 0, "roa": 2.4, "net_margin": 31, "operating_margin": 0,
         "gross_margin": 0, "revenue_growth": 17, "earnings_growth": 15,
         "revenue_cagr_3y": 16, "eps_cagr_3y": 17, "debt_to_equity": 6.0,
         "interest_coverage": 0, "current_ratio": 0, "quick_ratio": 0,
         "fcf_yield": 0, "promoter_holding": 26, "pledged_pct": 0,
         "years_since_listing": 28, "market_cap_cr": 350000, "price": 1760, "beta": 0.95}),

    # ============ FMCG — quality, expensive ================================
    DemoStock("HINDUNILVR", "Hindustan Unilever", "FMCG", "Personal & Household",
        {"pe": 55, "pb": 11, "ps": 8, "ev_ebitda": 38, "dividend_yield": 1.6,
         "roe": 21, "roce": 27, "roa": 17, "net_margin": 17, "operating_margin": 24,
         "gross_margin": 51, "revenue_growth": 4, "earnings_growth": 3,
         "revenue_cagr_3y": 10, "eps_cagr_3y": 9, "debt_to_equity": 0.0,
         "interest_coverage": 200, "current_ratio": 1.3, "quick_ratio": 0.9,
         "fcf_yield": 1.8, "promoter_holding": 62, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 580000, "price": 2460, "beta": 0.55}),
    DemoStock("ITC", "ITC", "FMCG", "Tobacco / Diversified",
        {"pe": 25, "pb": 7, "ps": 6, "ev_ebitda": 18, "dividend_yield": 3.4,
         "roe": 28, "roce": 36, "roa": 22, "net_margin": 28, "operating_margin": 35,
         "gross_margin": 58, "revenue_growth": 8, "earnings_growth": 10,
         "revenue_cagr_3y": 12, "eps_cagr_3y": 11, "debt_to_equity": 0.01,
         "interest_coverage": 500, "current_ratio": 3.5, "quick_ratio": 2.0,
         "fcf_yield": 3.6, "promoter_holding": 0, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 530000, "price": 425, "beta": 0.6}),
    DemoStock("NESTLEIND", "Nestle India", "FMCG", "Food",
        {"pe": 70, "pb": 65, "ps": 12, "ev_ebitda": 50, "dividend_yield": 1.0,
         "roe": 130, "roce": 145, "roa": 25, "net_margin": 17, "operating_margin": 23,
         "gross_margin": 55, "revenue_growth": 11, "earnings_growth": 18,
         "revenue_cagr_3y": 13, "eps_cagr_3y": 15, "debt_to_equity": 0.04,
         "interest_coverage": 90, "current_ratio": 1.6, "quick_ratio": 1.1,
         "fcf_yield": 1.5, "promoter_holding": 63, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 240000, "price": 2480, "beta": 0.5}),
    DemoStock("BRITANNIA", "Britannia Industries", "FMCG", "Food",
        {"pe": 60, "pb": 35, "ps": 7, "ev_ebitda": 42, "dividend_yield": 1.4,
         "roe": 60, "roce": 70, "roa": 22, "net_margin": 13, "operating_margin": 18,
         "gross_margin": 42, "revenue_growth": 7, "earnings_growth": 9,
         "revenue_cagr_3y": 10, "eps_cagr_3y": 11, "debt_to_equity": 0.55,
         "interest_coverage": 30, "current_ratio": 1.2, "quick_ratio": 0.7,
         "fcf_yield": 2.0, "promoter_holding": 51, "pledged_pct": 0,
         "years_since_listing": 26, "market_cap_cr": 130000, "price": 5400, "beta": 0.65}),

    # ============ Auto =====================================================
    DemoStock("MARUTI", "Maruti Suzuki", "Auto", "4-Wheelers",
        {"pe": 24, "pb": 4, "ps": 2.5, "ev_ebitda": 16, "dividend_yield": 1.0,
         "roe": 18, "roce": 24, "roa": 12, "net_margin": 9, "operating_margin": 12,
         "gross_margin": 25, "revenue_growth": 20, "earnings_growth": 35,
         "revenue_cagr_3y": 18, "eps_cagr_3y": 28, "debt_to_equity": 0.0,
         "interest_coverage": 300, "current_ratio": 1.0, "quick_ratio": 0.8,
         "fcf_yield": 3.5, "promoter_holding": 56, "pledged_pct": 0,
         "years_since_listing": 21, "market_cap_cr": 380000, "price": 12500, "beta": 0.95}),
    DemoStock("TATAMOTORS", "Tata Motors", "Auto", "4 & CV",
        {"pe": 13, "pb": 4, "ps": 0.9, "ev_ebitda": 7, "dividend_yield": 0.6,
         "roe": 31, "roce": 16, "roa": 7, "net_margin": 7, "operating_margin": 11,
         "gross_margin": 22, "revenue_growth": 23, "earnings_growth": 250,
         "revenue_cagr_3y": 15, "eps_cagr_3y": 80, "debt_to_equity": 1.2,
         "interest_coverage": 4, "current_ratio": 1.1, "quick_ratio": 0.7,
         "fcf_yield": 6.0, "promoter_holding": 46, "pledged_pct": 0,
         "years_since_listing": 32, "market_cap_cr": 280000, "price": 880, "beta": 1.4}),
    DemoStock("EICHERMOT", "Eicher Motors (Royal Enfield)", "Auto", "2-Wheelers",
        {"pe": 33, "pb": 8, "ps": 6, "ev_ebitda": 25, "dividend_yield": 1.0,
         "roe": 24, "roce": 32, "roa": 18, "net_margin": 19, "operating_margin": 25,
         "gross_margin": 43, "revenue_growth": 16, "earnings_growth": 25,
         "revenue_cagr_3y": 12, "eps_cagr_3y": 18, "debt_to_equity": 0.0,
         "interest_coverage": 500, "current_ratio": 2.8, "quick_ratio": 2.4,
         "fcf_yield": 2.8, "promoter_holding": 49, "pledged_pct": 0,
         "years_since_listing": 22, "market_cap_cr": 120000, "price": 4380, "beta": 0.85}),

    # ============ Pharma ====================================================
    DemoStock("SUNPHARMA", "Sun Pharma", "Pharma", "Generics",
        {"pe": 34, "pb": 5, "ps": 6, "ev_ebitda": 23, "dividend_yield": 0.9,
         "roe": 16, "roce": 19, "roa": 11, "net_margin": 18, "operating_margin": 28,
         "gross_margin": 70, "revenue_growth": 11, "earnings_growth": 17,
         "revenue_cagr_3y": 12, "eps_cagr_3y": 22, "debt_to_equity": 0.07,
         "interest_coverage": 50, "current_ratio": 3.5, "quick_ratio": 2.7,
         "fcf_yield": 2.4, "promoter_holding": 55, "pledged_pct": 0,
         "years_since_listing": 25, "market_cap_cr": 360000, "price": 1500, "beta": 0.7}),
    DemoStock("CIPLA", "Cipla", "Pharma", "Generics",
        {"pe": 27, "pb": 4, "ps": 4, "ev_ebitda": 17, "dividend_yield": 0.9,
         "roe": 14, "roce": 19, "roa": 11, "net_margin": 14, "operating_margin": 22,
         "gross_margin": 65, "revenue_growth": 7, "earnings_growth": 12,
         "revenue_cagr_3y": 9, "eps_cagr_3y": 18, "debt_to_equity": 0.03,
         "interest_coverage": 95, "current_ratio": 3.0, "quick_ratio": 2.3,
         "fcf_yield": 3.0, "promoter_holding": 33, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 130000, "price": 1620, "beta": 0.65}),

    # ============ Energy / Conglomerate =====================================
    DemoStock("RELIANCE", "Reliance Industries", "Conglomerate", "Energy / Retail / Telecom",
        {"pe": 27, "pb": 2.4, "ps": 1.6, "ev_ebitda": 13, "dividend_yield": 0.4,
         "roe": 9, "roce": 11, "roa": 5, "net_margin": 7, "operating_margin": 14,
         "gross_margin": 25, "revenue_growth": 3, "earnings_growth": 9,
         "revenue_cagr_3y": 14, "eps_cagr_3y": 10, "debt_to_equity": 0.45,
         "interest_coverage": 7, "current_ratio": 1.2, "quick_ratio": 0.8,
         "fcf_yield": 2.0, "promoter_holding": 50, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 1900000, "price": 2900, "beta": 1.0}),
    DemoStock("ONGC", "Oil and Natural Gas Corp", "Energy", "Upstream",
        {"pe": 8, "pb": 1.0, "ps": 0.7, "ev_ebitda": 4, "dividend_yield": 4.5,
         "roe": 17, "roce": 21, "roa": 8, "net_margin": 11, "operating_margin": 25,
         "gross_margin": 60, "revenue_growth": 4, "earnings_growth": 19,
         "revenue_cagr_3y": 7, "eps_cagr_3y": 15, "debt_to_equity": 0.30,
         "interest_coverage": 22, "current_ratio": 0.9, "quick_ratio": 0.6,
         "fcf_yield": 9.5, "promoter_holding": 58, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 350000, "price": 280, "beta": 1.1}),
    DemoStock("COALINDIA", "Coal India", "Energy", "Mining",
        {"pe": 7, "pb": 3.2, "ps": 1.6, "ev_ebitda": 4, "dividend_yield": 7.2,
         "roe": 51, "roce": 65, "roa": 22, "net_margin": 22, "operating_margin": 28,
         "gross_margin": 50, "revenue_growth": 0, "earnings_growth": 8,
         "revenue_cagr_3y": 9, "eps_cagr_3y": 17, "debt_to_equity": 0.10,
         "interest_coverage": 60, "current_ratio": 1.6, "quick_ratio": 1.2,
         "fcf_yield": 11.0, "promoter_holding": 63, "pledged_pct": 0,
         "years_since_listing": 14, "market_cap_cr": 280000, "price": 460, "beta": 1.0}),
    DemoStock("POWERGRID", "Power Grid Corp", "Utilities", "Transmission",
        {"pe": 19, "pb": 3.3, "ps": 5, "ev_ebitda": 11, "dividend_yield": 3.1,
         "roe": 19, "roce": 13, "roa": 5, "net_margin": 31, "operating_margin": 47,
         "gross_margin": 60, "revenue_growth": 5, "earnings_growth": 4,
         "revenue_cagr_3y": 7, "eps_cagr_3y": 6, "debt_to_equity": 1.4,
         "interest_coverage": 4, "current_ratio": 0.7, "quick_ratio": 0.6,
         "fcf_yield": 2.1, "promoter_holding": 51, "pledged_pct": 0,
         "years_since_listing": 18, "market_cap_cr": 290000, "price": 310, "beta": 0.7}),

    # ============ Cement / Materials ========================================
    DemoStock("ULTRACEMCO", "UltraTech Cement", "Cement", "Cement",
        {"pe": 35, "pb": 4.5, "ps": 4, "ev_ebitda": 20, "dividend_yield": 0.6,
         "roe": 13, "roce": 16, "roa": 8, "net_margin": 12, "operating_margin": 17,
         "gross_margin": 45, "revenue_growth": 14, "earnings_growth": 16,
         "revenue_cagr_3y": 16, "eps_cagr_3y": 13, "debt_to_equity": 0.18,
         "interest_coverage": 14, "current_ratio": 1.4, "quick_ratio": 0.9,
         "fcf_yield": 1.8, "promoter_holding": 60, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 300000, "price": 10500, "beta": 0.95}),

    # ============ Metals — cyclical, leveraged ==============================
    DemoStock("TATASTEEL", "Tata Steel", "Metals", "Steel",
        {"pe": 22, "pb": 2.2, "ps": 1.1, "ev_ebitda": 8, "dividend_yield": 2.6,
         "roe": 11, "roce": 9, "roa": 4, "net_margin": 4, "operating_margin": 12,
         "gross_margin": 30, "revenue_growth": -3, "earnings_growth": -45,
         "revenue_cagr_3y": 7, "eps_cagr_3y": 12, "debt_to_equity": 1.0,
         "interest_coverage": 4, "current_ratio": 0.7, "quick_ratio": 0.5,
         "fcf_yield": 3.0, "promoter_holding": 33, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 200000, "price": 165, "beta": 1.35}),
    DemoStock("JSWSTEEL", "JSW Steel", "Metals", "Steel",
        {"pe": 26, "pb": 3.0, "ps": 1.5, "ev_ebitda": 10, "dividend_yield": 0.8,
         "roe": 13, "roce": 11, "roa": 4, "net_margin": 5, "operating_margin": 15,
         "gross_margin": 32, "revenue_growth": 6, "earnings_growth": 5,
         "revenue_cagr_3y": 12, "eps_cagr_3y": 7, "debt_to_equity": 1.05,
         "interest_coverage": 4, "current_ratio": 0.8, "quick_ratio": 0.5,
         "fcf_yield": 2.5, "promoter_holding": 44, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 220000, "price": 900, "beta": 1.3}),

    # ============ Telecom ===================================================
    DemoStock("BHARTIARTL", "Bharti Airtel", "Telecom", "Wireless",
        {"pe": 60, "pb": 7, "ps": 4.5, "ev_ebitda": 10, "dividend_yield": 0.5,
         "roe": 11, "roce": 9, "roa": 3, "net_margin": 8, "operating_margin": 25,
         "gross_margin": 60, "revenue_growth": 7, "earnings_growth": 200,
         "revenue_cagr_3y": 13, "eps_cagr_3y": 35, "debt_to_equity": 1.8,
         "interest_coverage": 3, "current_ratio": 0.4, "quick_ratio": 0.4,
         "fcf_yield": 3.5, "promoter_holding": 53, "pledged_pct": 0,
         "years_since_listing": 22, "market_cap_cr": 900000, "price": 1550, "beta": 0.85}),

    # ============ High-debt / high-risk stress test =========================
    DemoStock("ADANIENT", "Adani Enterprises", "Diversified", "Holding",
        {"pe": 80, "pb": 9, "ps": 1.8, "ev_ebitda": 30, "dividend_yield": 0.1,
         "roe": 9, "roce": 11, "roa": 3, "net_margin": 2, "operating_margin": 7,
         "gross_margin": 18, "revenue_growth": 1, "earnings_growth": -15,
         "revenue_cagr_3y": 35, "eps_cagr_3y": 25, "debt_to_equity": 1.9,
         "interest_coverage": 2, "current_ratio": 0.9, "quick_ratio": 0.5,
         "fcf_yield": -1.0, "promoter_holding": 74, "pledged_pct": 3,
         "years_since_listing": 30, "market_cap_cr": 280000, "price": 2450, "beta": 1.6}),
    DemoStock("VODAIDEA", "Vodafone Idea", "Telecom", "Wireless",
        {"pe": 0, "pb": -2.0, "ps": 1.0, "ev_ebitda": 18, "dividend_yield": 0,
         "roe": -120, "roce": -6, "roa": -10, "net_margin": -70, "operating_margin": 15,
         "gross_margin": 35, "revenue_growth": 1, "earnings_growth": 0,
         "revenue_cagr_3y": 0, "eps_cagr_3y": 0, "debt_to_equity": 8.0,
         "interest_coverage": 0.3, "current_ratio": 0.3, "quick_ratio": 0.3,
         "fcf_yield": -8.0, "promoter_holding": 38, "pledged_pct": 12,
         "years_since_listing": 17, "market_cap_cr": 65000, "price": 14, "beta": 1.5}),

    # ============ Quality compounders mid-cap ===============================
    DemoStock("ASIANPAINT", "Asian Paints", "Paints", "Decoratives",
        {"pe": 53, "pb": 13, "ps": 5.5, "ev_ebitda": 35, "dividend_yield": 1.0,
         "roe": 27, "roce": 38, "roa": 17, "net_margin": 11, "operating_margin": 18,
         "gross_margin": 40, "revenue_growth": 1, "earnings_growth": -3,
         "revenue_cagr_3y": 15, "eps_cagr_3y": 9, "debt_to_equity": 0.04,
         "interest_coverage": 70, "current_ratio": 1.7, "quick_ratio": 1.0,
         "fcf_yield": 1.7, "promoter_holding": 53, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 260000, "price": 2700, "beta": 0.65}),
    DemoStock("TITAN", "Titan Company", "Consumer Discretionary", "Jewellery",
        {"pe": 90, "pb": 32, "ps": 6, "ev_ebitda": 60, "dividend_yield": 0.3,
         "roe": 33, "roce": 32, "roa": 12, "net_margin": 7, "operating_margin": 11,
         "gross_margin": 25, "revenue_growth": 25, "earnings_growth": 15,
         "revenue_cagr_3y": 28, "eps_cagr_3y": 20, "debt_to_equity": 0.7,
         "interest_coverage": 18, "current_ratio": 1.3, "quick_ratio": 0.4,
         "fcf_yield": 1.0, "promoter_holding": 53, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 320000, "price": 3600, "beta": 0.9}),
    DemoStock("PIDILITIND", "Pidilite Industries (Fevicol)", "Chemicals", "Adhesives",
        {"pe": 75, "pb": 17, "ps": 9, "ev_ebitda": 50, "dividend_yield": 0.5,
         "roe": 23, "roce": 30, "roa": 17, "net_margin": 13, "operating_margin": 21,
         "gross_margin": 50, "revenue_growth": 8, "earnings_growth": 25,
         "revenue_cagr_3y": 14, "eps_cagr_3y": 13, "debt_to_equity": 0.02,
         "interest_coverage": 250, "current_ratio": 2.5, "quick_ratio": 1.8,
         "fcf_yield": 1.4, "promoter_holding": 70, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 140000, "price": 2750, "beta": 0.55}),

    # ============ Dividend yield specialists ================================
    DemoStock("HINDPETRO", "Hindustan Petroleum", "Energy", "Oil Marketing",
        {"pe": 5, "pb": 1.1, "ps": 0.1, "ev_ebitda": 4, "dividend_yield": 6.0,
         "roe": 23, "roce": 18, "roa": 5, "net_margin": 2, "operating_margin": 4,
         "gross_margin": 8, "revenue_growth": 4, "earnings_growth": 150,
         "revenue_cagr_3y": 12, "eps_cagr_3y": 22, "debt_to_equity": 0.8,
         "interest_coverage": 6, "current_ratio": 0.9, "quick_ratio": 0.4,
         "fcf_yield": 5.0, "promoter_holding": 55, "pledged_pct": 0,
         "years_since_listing": 30, "market_cap_cr": 65000, "price": 460, "beta": 1.1}),
    DemoStock("VEDL", "Vedanta", "Metals", "Diversified",
        {"pe": 17, "pb": 3.0, "ps": 0.8, "ev_ebitda": 5, "dividend_yield": 8.5,
         "roe": 28, "roce": 25, "roa": 6, "net_margin": 5, "operating_margin": 24,
         "gross_margin": 40, "revenue_growth": -5, "earnings_growth": -20,
         "revenue_cagr_3y": 11, "eps_cagr_3y": 8, "debt_to_equity": 2.1,
         "interest_coverage": 2, "current_ratio": 0.8, "quick_ratio": 0.5,
         "fcf_yield": 6.0, "promoter_holding": 62, "pledged_pct": 100,
         "years_since_listing": 25, "market_cap_cr": 175000, "price": 470, "beta": 1.5}),
]


def by_ticker() -> dict[str, DemoStock]:
    return {s.ticker: s for s in DEMO_STOCKS}
